### ISSUE TITLE
[undefined].schema is trying multiple times to be accessed

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#105]
```
JSONAPI-TS:  TypeError: Cannot read property 'schema' of undefined    at ResourceProcessor.get (/c/dev/jsonapi-ts/src/processors/knex-processor.ts:73:47)
    at ResourceProcessor.execute (/c/dev/jsonapi-ts/src/processors/operation-processor.ts:20:60)    at Application.executeOperation (/c/dev/jsonapi-ts/src/application.ts:29:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Weird thing about this bug is that apparently doesn't break functionality, but it floods the console for every request I do, using the dummy app.

**Comment by joelalejandro** [comment]
Nevermind. Chrome is stupid.
