### ISSUE TITLE
[GET] resource should return empty array if empty

### ISSUE THREAD

**Issue by betocantu93** [ebryn/jsonapi-ts#116]
With a clean db table, lets say, `comments` the endpoint `GET[/comments]` errors out with this message 

version `0.1.23`

```
JSONAPI-TS:  TypeError: Cannot read property 'type' of undefined
    at Application.serializeResources (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/application.ts:137:60)
    at Application.buildOperationResponse (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/application.ts:125:44)
[timestamp:2019-05-04T21:05:00.903Z] [level:info] [message:IncomingRequest] [url:/comments] [queryParams:undefined] [body:{}] [headers:{"client":"catalog","cache-control":"no-cache","postman-token":"1d0dc4d1-14e4-4fb2-a813-88336e489a06","user-agent":"PostmanRuntime/7.6.0","accept":"*/*","host":"localhost:3000","accept-encoding":"gzip, deflate","connection":"keep-alive"}]
[timestamp:2019-05-04T21:05:00.903Z] [level:error] [message:OutgoingResponse] [status:500] [body:{"errors":[{"status":500,"code":"unhandled_error"}]}] [headers:{"client":"catalog","cache-control":"no-cache","postman-token":"1d0dc4d1-14e4-4fb2-a813-88336e489a06","user-agent":"PostmanRuntime/7.6.0","accept":"*/*","host":"localhost:3000","accept-encoding":"gzip, deflate","connection":"keep-alive"}]
```

This only happens when the table is empty, if I manually add a record, the endpoint works.

**Comment by betocantu93** [comment]
UPDATE:

version `0.1.25`

Returns 
```
{
  data: null
}
```
But [spec](https://jsonapi.org/format/#fetching-resources-responses) suggest: 

![image](https://user-images.githubusercontent.com/9092644/57184846-74c1a980-6e87-11e9-85f1-9184eb475135.png)
