### ISSUE TITLE
Internal server errror when sending authorization header

### ISSUE THREAD

**Issue by betocantu93** [ebryn/jsonapi-ts#117]
Any authenticated request (by authenticated I mean sending authorization: Bearer 1231...) crashes the request. I just get Internal Server Error with this error showing in Node.

```
[timestamp:2019-05-05T16:47:04.384Z] [level:info] [message:API ready] [port:3000]
  TypeError: this.knex is not a function
      at UserProcessor.getQuery (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/knex-processor.ts:93:17)
      at UserProcessor.get (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/knex-processor.ts:116:46)
      at UserProcessor.identify (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/src/processors/userProcessor.ts:11:18)
      at UserProcessor.execute (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/operation-processor.ts:27:56)
      at Application.executeOperation (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/application.ts:74:36)
      at process._tickCallback (internal/process/next_tick.js:68:7)
(node:53824) Warning: a promise was rejected with a non-error: [object Object]
(node:53824) Warning: a promise was rejected with a non-error: [object Object]
JSONAPI-TS:  TypeError: (intermediate value) is not iterable
    at handleJsonApiEndpoint (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/middlewares/json-api-koa.ts:104:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[timestamp:2019-05-05T16:47:13.108Z] [level:info] [message:IncomingRequest] [url:/users/49] [queryParams:undefined] [body:{}] [headers:{"client":"catalog","cache-control":"no-cache","postman-token":"536a257d-b177-49c1-9200-0e7ec8dc19f2","user-agent":"PostmanRuntime/7.6.0","accept":"*/*","host":"localhost:3000","accept-encoding":"gzip, deflate","connection":"keep-alive"}]
[timestamp:2019-05-05T16:47:13.109Z] [level:error] [message:OutgoingResponse] [status:500] [body:{"errors":[{"status":500,"code":"unhandled_error"}]}] [headers:{"client":"catalog","cache-control":"no-cache","postman-token":"536a257d-b177-49c1-9200-0e7ec8dc19f2","user-agent":"PostmanRuntime/7.6.0","accept":"*/*","host":"localhost:3000","accept-encoding":"gzip, deflate","connection":"keep-alive"}]
{ status: 401, code: 'unauthorized' }
  TypeError: this.knex is not a function
      at UserProcessor.getQuery (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/knex-processor.ts:93:17)
      at UserProcessor.get (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/knex-processor.ts:116:46)
      at UserProcessor.identify (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/src/processors/userProcessor.ts:11:18)
      at UserProcessor.execute (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/processors/operation-processor.ts:27:56)
      at Application.executeOperation (/Users/betocantu93/Documents/prototypal/untitled-chat-project-api/node_modules/@ebryn/jsonapi-ts/src/application.ts:74:36)
      at process._tickCallback (internal/process/next_tick.js:68:7)
e
```

**Comment by spersico** [comment]
This has been fixed... I believe yesterday. If you are referring to chat-api, I haven't released the fix there yet
