### ISSUE TITLE
type detection isn't working correctly

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#29]
When defining compound type names like `supplyCategory`, the OperationProcessor.resourceFor() function fails to return the correct type.

Expected: `SupplyCategory`
Received: `Supplycategory`

Putting some logs revealed this:

```
2019-02-18T14:13:28.597530346Z checking if  SupplyCategory  matches  Supplycategory
```

The following error was thrown after:
```
2019-02-18T14:13:28.598537676Z JSONAPI-TS:  TypeError: resourceClass is not a constructor
2019-02-18T14:13:28.598555998Z     at records.map.record (/opt/app/node_modules/@ebryn/jsonapi-ts/dist/processors/knex-processor.js:54:20)
2019-02-18T14:13:28.598561872Z     at Array.map (<anonymous>)
2019-02-18T14:13:28.598566464Z     at KnexProcessor.convertToResources (/opt/app/node_modules/@ebryn/jsonapi-ts/dist/processors/knex-processor.js:49:24)
2019-02-18T14:13:28.598574428Z     at KnexProcessor.get (/opt/app/node_modules/@ebryn/jsonapi-ts/dist/processors/knex-processor.js:19:21)
2019-02-18T14:13:28.598578273Z     at <anonymous>
```

**Comment by joelalejandro** [comment]
Problem was due to `capitalize()` exceeding its responsibility. Granted, it upper-cased the first character of a string but **also** lower-cased the rest. 

f7c074b replaces this greedy function with a simple replace operation:

```
export default function capitalize(str: string) {
  return str.replace(/^\w/, chr => chr.toUpperCase());
}
```
